services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${NGINX_BASE_IMAGE:-nginx:alpine}
    container_name: lemp_nginx
    ports:
      - "8080:80"
    # Note: Only Nginx (8080), Adminer (8081), and Uptime Kuma (3001) are exposed to host.
    # MySQL (3306) and PHP-FPM (9000) are internal-only on the lemp-network.
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
    networks:
      - lemp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      retries: 3
      start_period: 40s

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${PHP_BASE_IMAGE:-php:8.2-fpm-alpine}
    container_name: lemp_php
    volumes:
      - ./www:/var/www/html
    environment:
      - DB_HOST=${DB_HOST:-mysql}
      - DB_NAME=${DB_NAME:-my_app_db}
      - DB_USER=${DB_USER:-app_user}
      - DB_PASSWORD=${DB_PASSWORD:-app_pass}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lemp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm"]
      interval: 30s
      retries: 3
      start_period: 40s
    # dev-only diagnostics are gated by APP_ENV in the app code

  mysql:
    image: mysql:8.0
    container_name: lemp_mysql
    environment:
      # MySQL's built-in initialization variables
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpass}
      - MYSQL_DATABASE=${DB_NAME:-my_app_db}
      - MYSQL_USER=${DB_USER:-app_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-app_pass}
      # Additional security settings
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lemp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  adminer:
    image: adminer:latest
    container_name: lemp_adminer
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lemp-network
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: lemp_uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lemp-network
    restart: unless-stopped

networks:
  lemp-network:
    driver: bridge

volumes:
  mysql_data:
  uptime_data: