blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/Soumalya-De/LEMP-Sentinel/security/policy
    about: Please report security vulnerabilities privately per our security policy.
