name: Security - nightly image scan

on:
  schedule:
    - cron: '0 2 * * *' # nightly at 02:00 UTC
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    env:
      # Ensure compose builds have explicit defaults in this workflow too
      NGINX_BASE_IMAGE: nginx:alpine
      PHP_BASE_IMAGE: php:8.2-fpm-alpine
      DB_HOST: mysql
      DB_NAME: my_app_db
      DB_USER: app_user
      DB_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: rootpass
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Trivy
        run: |
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          sudo apt-get update && sudo apt-get install -y jq

      - name: Build images (local)
        run: |
          docker compose build --pull

      - name: Trivy scan (PRs - informational)
        if: github.event_name == 'pull_request'
        run: |
          set -e
          mkdir -p trivy-results
          for img in $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -E 'nginx:|php:' | sort -u); do
            echo "Scanning $img (informational)"
            safe=$(echo "$img" | sed 's/[^A-Za-z0-9._-]/_/g')
            out=trivy-results/trivy-${safe}.sarif
            json=trivy-results/trivy-${safe}.json
            trivy image --severity HIGH,CRITICAL --format sarif --output "$out" --timeout 5m "$img" || true
            trivy image --severity HIGH,CRITICAL --format json  --output "$json"  --timeout 5m "$img" || true
          done
          ls -lah trivy-results || true

      - name: Create Trivy summary (PRs)
        if: github.event_name == 'pull_request'
        run: |
          echo "# Trivy Summary" > trivy-summary.md
          echo "# Proposed .trivyignore entries (review before use)" > trivy-proposed-ignore.txt
          echo "# Add a rationale above each CVE and link to a tracking issue." >> trivy-proposed-ignore.txt
          for f in trivy-*.json; do
            [ -f "$f" ] || continue
            img=$(echo "$f" | sed 's/^trivy-//' | sed 's/\.json$//')
            crit=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' "$f")
            high=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' "$f")
            echo "\n## $img" >> trivy-summary.md
            echo "- CRITICAL: $crit" >> trivy-summary.md
            echo "- HIGH: $high" >> trivy-summary.md
            jq -r '.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL") | .VulnerabilityID' "$f" | sort -u | sed 's/^/# CVE review required\n/' | sed 's/^# CVE review required$//' >> trivy-proposed-ignore.txt
          done

      - name: Comment Trivy summary on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('trivy-summary.md','utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

      - name: Upload proposed ignore file (PRs)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-proposed-ignore
          path: trivy-proposed-ignore.txt

      - name: Trivy scan (main/schedule - blocking on HIGH/CRITICAL)
        if: github.event_name != 'pull_request'
        working-directory: ${{ github.workspace }}
        run: |
          set -euo pipefail
          mkdir -p "${GITHUB_WORKSPACE}/trivy-results"
          scan_rc=0
          docker images --format '{{.Repository}}:{{.Tag}}' | grep -E 'nginx:|php:' | sort -u | while read -r img; do
            safe=$(echo "$img" | sed 's#[^A-Za-z0-9._-]#_#g')
            out="${GITHUB_WORKSPACE}/trivy-results/${safe}.sarif"
            echo "Scanning $img -> $out"
            trivy image --format sarif --severity HIGH,CRITICAL --output "$out" "$img" || scan_rc=$?
          done
          ls -lah "${GITHUB_WORKSPACE}/trivy-results" || true
          exit "$scan_rc"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Upload SARIF results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: ${{ github.workspace }}/trivy-results/*.sarif

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results
          category: trivy
